// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class FileStatus {
  final String path;
  final FileStatusKind status;

  const FileStatus({required this.path, required this.status});

  @override
  int get hashCode => path.hashCode ^ status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileStatus &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          status == other.status;
}

enum FileStatusKind {
  modified,
  added,
  deleted,
  renamed,
  copied,
  untracked,
  conflicted,
}

class RepoStatus {
  final String path;
  final bool isClean;
  final List<FileStatus> files;

  const RepoStatus({
    required this.path,
    required this.isClean,
    required this.files,
  });

  @override
  int get hashCode => path.hashCode ^ isClean.hashCode ^ files.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RepoStatus &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          isClean == other.isClean &&
          files == other.files;
}
